export enum BackendErrors {
  UNDEFINED_ERROR = 'UNDEFINED_ERROR',
  USER_DIDNT_PAY_FOR_COURSE = 'USER_DIDNT_PAY_FOR_COURSE',
  AMPLIFY_API_ERROR = 'AMPLIFY_API_ERROR',
  CORS_ERROR = 'CORS_ERROR',
  NOT_AUTHORIZED = 'NOT_AUTHORIZED',
  AMPLIFY_ADDING_DOMAIN_ERROR = 'AMPLIFY_ADDING_DOMAIN_ERROR',
  COURSE_DOMAIN_ALREADY_EXISTS = 'COURSE_DOMAIN_ALREADY_EXISTS',
  GETTING_COURSE_DOMAIN_ERROR = 'GETTING_COURSE_DOMAIN_ERROR',
}
