export enum CourseLandingPageSections {
  FEATURES = 'FEATURES',
  ABOUT_COURSE = 'ABOUT_COURSE',
  SUBJECTS = 'SUBJECTS',
  COURSE_CONTENT = 'COURSE_CONTENT',
  RECOMMENDED_COURSES = 'RECOMMENDED_COURSES',
}
